using EH.Models.Xpm;
using Mapster;

namespace EH.Shared.SdocJsonToXpmConverter.Mapping.Configs
{
    public class EventMappingConfig : IRegister
    {
        public void Register( TypeAdapterConfig config )
        {
            // Mapping config for EH.Models.Xpm.Event and dependents.
            TypeAdapterConfig<SdocAdapter.Root, Event>.ForType()
                .Map(dest => dest.AlertAlertCategory, src => src.Alerts.AlertCategory)
                .Map(dest => dest.AlertAlertCode, src => src.Alerts.AlertCode)
                .Map(dest => dest.AlertAlertDescription, src => src.Alerts.AlertDescription)
                .Map(dest => dest.AlertAlertResolved, src => src.Alerts.AlertResolved)
                .Map(dest => dest.AlertAlertSource, src => src.Alerts.AlertSource)
                .Map(dest => dest.AlertAlertStatus, src => src.Alerts.AlertStatus)
                .Map(dest => dest.AlertCompanyId, src => src.Alerts.CompanyID)
                .Map(dest => dest.AlertDateUpdated, src => src.Alerts.DateUpdated)
                .Map(dest => dest.AlertECarePatientAccountAlertsId, src => src.Alerts.Care_Patient_Account_Alerts_ID)
                .Map(dest => dest.AlertEVNUserId, src => src.Alerts.EVN_UserID)
                .Map(dest => dest.AlertNeboUserId, src => src.Alerts.NeboUserID)
                .Map(dest => dest.AlertProductSource, src => src.Alerts.ProductSource)
                .Map(dest => dest.AlertProtocol, src => src.Alerts.Protocol)
                .Map(dest => dest.BatchRowId, src => src.MessageEvent.BatchRowId)
                .Map(dest => dest.Deserializer, src => src.MessageHeader.Deserializer)
                .Map(dest => dest.DoNotOverWriteInsurance, src => src.MessageEvent.DoNotOverWriteInsurance)
                .Map(dest => dest.EventReasonCode, src => src.MessageEvent.EventReasonCode)
                .Map(dest => dest.IpsMessageId, src => src.MessageEvent.IPS_Message_ID)
                .Map(dest => dest.IsBatchTrigger, src => src.MessageEvent.IsBatchTrigger)
                .Map(dest => dest.IsTempAccount, src => src.MessageEvent.IsTempAccount)
                .Map(dest => dest.MessageEventVersion, src => src.MessageEvent.MessageEventVersion)
                .Map(dest => dest.MessageHeader, src => src.Adapt<MessageHeader>())
                .Map(dest => dest.MPIWriteAccountInsurance, src => src.MessageEvent.MPIWriteAccountInsurance)
                .Map(dest => dest.OperatorId, src => src.Authentication.UserMnemonic)
                .Map(dest => dest.OrcaInstId, src => src.MessageEvent.OrcaInstID)
                .Map(dest => dest.OriginalTriggeredUser, src => src.MessageEvent.OriginalTriggeredUser)
                .Map(dest => dest.OverRideResponseReuse, src => src.MessageHeader.OverRideResponseReuse)
                .Map(dest => dest.Payload, src => src.MSP.Payload)
                .Map(dest => dest.PopPic, src => src.MessageEvent.PopPic)
                .Map(dest => dest.ScanAndTriggerId, src => src.MessageEvent.ScanAndTriggerId)
                .Map(dest => dest.SequenceId, src => src.MessageEvent.SequenceID)
                .Map(dest => dest.Softwares, src => new List<Software>())
                .Map(dest => dest.TestMode, src => src.MessageEvent.TestMode)
                .Map(dest => dest.TpIdentifier, src => src.Authentication.TradingPartnerID)
                .Map(dest => dest.UpdateIPSTempAccount, src => src.MessageEvent.UpdateIPS_TempAccount)
                .Map(dest => dest.UseForHL7PostbackTemplateOnly, src => src.MessageEvent.UseForHL7PostbackTemplateOnly)
                .Map(dest => dest.ValidHL7PostbackTemplate, src => src.MessageHeader.ValidHL7PostbackTemplate)
                .Map(dest => dest.WrapperMetadata, src => new WrapperMetadata())
                .IgnoreNonMapped( true );

            TypeAdapterConfig<SdocAdapter.MessageEvent, Event>.ForType()
                .Map(dest => dest.AlertECarePatientAccountAlertsId, src => src.eCare_Patient_Account_Alerts_ID)
                .Map(dest => dest.BatchBinNumber, src => src.BatchBinNumber)
                .Map(dest => dest.BatchFileName, src => src.BatchFileName)
                .Map(dest => dest.BatchRowId, src => src.BatchRowId)
                .Map(dest => dest.BypassAccountFinder, src => src.BypassAccountFinder)
                .Map(dest => dest.CancellationMessageType, src => src.CancellationMessageType)
                .Map(dest => dest.ClientRequestedEventIndicator, src => src.ClientRequestedEventIndicator)
                .Map(dest => dest.ConcatenateAISActionCodes, src => src.ConcatenateAISActionCodes)
                .Map(dest => dest.ConcatenateAssignedLocation, src => src.ConcatenateAssignedLocation)
                .Map(dest => dest.ConcatenateProcedureCodes, src => src.ConcatenateProcedureCodes)
                .Map(dest => dest.CreateDate, src => src.CreateDate)
                .Map(dest => dest.DeactivateCDInsurances, src => src.DeactivateCDInsurances)
                .Map(dest => dest.Deserializer, src => src.Deserializer)
                .Map(dest => dest.DoNotOverWriteInsurance, src => src.DoNotOverWriteInsurance)
                .Map(dest => dest.DoNotStoreHL7PostbackTemplate, src => src.DoNotStoreHL7PostbackTemplate)
                .Map(dest => dest.DoNotWriteToWC, src => src.DoNotWriteToWC)
                .Map(dest => dest.EventReasonCode, src => src.EventReasonCode)
                .Map(dest => dest.FASSetSearchTypeByAdditionalSettings, src => src.FAS_SetSearchType_ByAdditionalSettings)
                .Map(dest => dest.ForceAutoRun, src => src.ForceAutoRun)
                .Map(dest => dest.ForceAutoRunAuth, src => src.ForceAutoRunAuth)
                .Map(dest => dest.ForceAutoRunAV, src => src.ForceAutoRunAV)
                .Map(dest => dest.ForceAutoRunEV, src => src.ForceAutoRunEV)
                .Map(dest => dest.ForceAutoRunMedNec, src => src.ForceAutoRunMedNec)
                .Map(dest => dest.ForceAutoRunPayNav, src => src.ForceAutoRunPayNav)
                .Map(dest => dest.FoundCoverageDiscovery, src => src.FoundCoverageDiscovery)
                .Map(dest => dest.HasSnTInsertedEver, src => src.HasSnTInsertedEver)
                .Map(dest => dest.HasSnTTriggeredEver, src => src.HasSnTTriggeredEver)
                .Map(dest => dest.InsertBatchRecordError, src => src.InsertBatchRecordError)
                .Map(dest => dest.IPSMessageType, src => src.IPSMessageType)
                .Map(dest => dest.IsBatchTrigger, src => src.IsBatchTrigger)
                .Map(dest => dest.IsCDB2IRequest, src => src.IsCDB2IRequest)
                .Map(dest => dest.JoinOnInsuranceMnemonicOnly, src => src.JoinOnInsuranceMnemonicOnly)
                .Map(dest => dest.MessageInputType, src => src.MessageInputType)
                .Map(dest => dest.MPIUpdateInsurancesOnly, src => src.MPIUpdateInsurancesOnly)
                .Map(dest => dest.MPIWriteAccountInsurance, src => src.MPIWriteAccountInsurance)
                .Map(dest => dest.NextBarDisplayResetMsg, src => src.NextBarDisplayResetMsg)
                .Map(dest => dest.OnDemandCDRequest, src => src.OnDemandCDRequest)
                .Map(dest => dest.OnDemandFASRequest, src => src.OnDemandFASRequest)
                .Map(dest => dest.PersonType, src => src.PersonType)
                .Map(dest => dest.PopPic, src => src.AddressToValidate)
                .Map(dest => dest.PopPic, src => src.PopPic)
                .Map(dest => dest.RemoveProcedureCodes, src => src.RemoveProcedureCodes)
                .Map(dest => dest.ResponseChainingOn, src => src.ResponseChainingOn)
                .Map(dest => dest.ResponseQueue, src => src.ResponseQueue)
                .Map(dest => dest.ROMessageType, src => src.RO_MessageType)
                .Map(dest => dest.SDocBaseMessageSpecification, src => src.SDocBaseMessageSpecification)
                .Map(dest => dest.SequenceId, src => src.SequenceID)
                .Map(dest => dest.SkipAllIRules, src => src.SkipAllIRules)
                .Map(dest => dest.SocanovaSendTime, src => src.SocanovaSendTime)
                .Map(dest => dest.SourceInterface, src => src.SourceInterface)
                .Map(dest => dest.StrainCorrelationId, src => src.StrainCorrelationId)
                .Map(dest => dest.SubmitterIdentificationNumber, src => src.SubmitterIdentificationNumber)
                .Map(dest => dest.TestMode, src => src.TestMode)
                .Map(dest => dest.UseForHL7PostbackTemplateOnly, src => src.UseForHL7PostbackTemplateOnly)
                .Map(dest => dest.UserTriggered, src => src.UserTriggered)
                .Map(dest => dest.UseSelectedServiceType, src => src.UseSelectedServiceType)
                .Map(dest => dest.ValidHL7PostbackTemplate, src => src.ValidHL7PostbackTemplate)

                .IgnoreNonMapped(true);

            TypeAdapterConfig<SdocAdapter.Root, MessageHeader>.ForType()
                .Map(dest => dest.AdminTxGuid, src => src.MessageHeader.AdminTxGUID)
                .Map(dest => dest.AllowDemoSearchClientMasterPatientId, src => src.MessageHeader.AllowDemoSearch_ClientMasterPatientID)
                .Map(dest => dest.AllowNewRequests, src => src.MessageHeader.AllowNewRequests)
                .Map(dest => dest.BaseMessageType, src => src.MessageEvent.SDocBaseMessageType)
                .Map(dest => dest.BatchTxGuid, src => src.MessageHeader.BatchTxGUID)
                .Map(dest => dest.ClientAdminTimeZone, src => src.MessageHeader.ClientAdminTimeZone)
                .Map(dest => dest.ClientMnemonic, src => src.Authentication.ClientMnemonic)
                .Map(dest => dest.ClientNpi, src => src.MessageHeader.ClientNPI)
                .Map(dest => dest.ClientRequestedEventIndicator, src => src.MessageEvent.ClientRequestedEventIndicator)
                .Map(dest => dest.ClientSpecifiedClientId, src => src.Authentication.ClientSpecificClientID)
                .Map(dest => dest.ConfigClientId, src => src.MessageHeader.ConfigClientId)
                .Map(dest => dest.ConfigTradingPartner, src => src.MessageHeader.ConfigTradingPartner)
                .Map(dest => dest.ConfigUserId, src => src.MessageHeader.ConfigUserId)
                .Map(dest => dest.CorrelationId278, src => src.MessageHeader.CorrelationID_278)
                .Map(dest => dest.CountryCode, src => src.MessageHeader.CountryCode)
                .Map(dest => dest.DateOfMessageProcessed, src => src.MessageHeader.DateOfMessageProcessed)
                .Map(dest => dest.DateTimeOfEvent, src => src.MessageEvent.DateOfMessage)
                .Map(dest => dest.DateTimeOfEvent, src => src.MessageEvent.DateTimeOfEvent)
                .Map(dest => dest.EncounterStateId, src => src.MessageHeader.EncounterStateId)
                .Map(dest => dest.ExperianClientId, src => src.Authentication.PassportClientID)
                .Map(dest => dest.ExperianUserId, src => src.Authentication.PassportUserID)
                .Map(dest => dest.ExpirationDate, src => src.MessageHeader.ExpirationDate)
                .Map(dest => dest.HisUserId, src => src.MessageHeader.HIS_UserID)
                .Map(dest => dest.IntelliAvResponse_NextPayerCode, src => src.MessageHeader.IntelliAvResponse_NextPayerCode)
                .Map(dest => dest.IsaInterchangeControlNumber, src => src.MessageHeader.ISAInterchangeControlNumber)
                .Map(dest => dest.IsIpsMessage, src => src.MessageHeader.Is_IPS_Message)
                .Map(dest => dest.IsQ22PaymentAdvisor, src => src.MessageHeader.Q22_IsPaymentAdvisor)
                .Map(dest => dest.IsVendorRequest, src => src.MessageHeader.IsVendorRequest)
                .Map(dest => dest.LoadFromMpiIncludeState, src => src.MessageHeader.LoadFromMPI_IncludeState)
                .Map(dest => dest.MessageControlId, src => src.MessageHeader.MessageControlID)
                .Map(dest => dest.MessageCorrelationId, src => src.MessageHeader.CorrelationID)
                .Map(dest => dest.MessageDelaySeconds, src => src.MessageHeader.MessageDelaySeconds)
                .Map(dest => dest.MessageEventFormat, src => src.MessageEvent.MessageEventFormat)
                .Map(dest => dest.MessageEventType, src => src.MessageEvent.MessageEventType)
                .Map(dest => dest.MessageQueryName, src => src.MessageHeader.MessageQueryName)
                .Map(dest => dest.MessageWrapped, src => src.MessageHeader.MessageWrapped)
                .Map(dest => dest.MsmqResponseQueue, src => src.MessageHeader.MsmqResponseQueue)
                .Map(dest => dest.MsmqResponseQueue, src => src.MessageHeader.ResponseQueue)
                .Map(dest => dest.MultiTransactionMode, src => src.MessageHeader.MultiTransactionMode)
                .Map(dest => dest.NeboAccountId, src => src.MessageHeader.NeboAccountID)
                .Map(dest => dest.NewEligibilityEvent, src => src.MessageHeader.NewEligibilityEvent)
                .Map(dest => dest.OrcaInstanceId, src => src.MessageHeader.OrcaInstanceId)
                .Map(dest => dest.PassportDepartment, src => src.Authentication.PassportDepartment, src => !string.IsNullOrWhiteSpace(src.Authentication.PassportDepartment))
                .Map(dest => dest.PassportDepartment, src => src.PatientVisit.Department, src => string.IsNullOrWhiteSpace(src.Authentication.PassportDepartment))
                .Map(dest => dest.PlatformFlag, src => src.MessageHeader.PlatformFlag)
                .Map(dest => dest.PpaeInstanceId, src => src.MessageHeader.PpaeInstanceId)
                .Map(dest => dest.PrincipalLanguageOfMessage, src => src.MessageHeader.PrincipalLanguageOfMessage)
                .Map(dest => dest.ProcessingId, src => src.MessageHeader.PlatformFlag)
                .Map(dest => dest.Q22CorrelationId, src => src.MessageHeader.Q22_CorrelationID)
                .Map(dest => dest.ReasonforRouting, src => src.MessageHeader.ReasonforRouting)
                .Map(dest => dest.ReceivingFacility, src => src.MessageHeader.ReceivingFacility)
                .Map(dest => dest.StateId, src => src.MessageHeader.StateID)
                .Map(dest => dest.SubmittedMessageType, src => src.MessageHeader.SubmittedMessageType)
                .Map(dest => dest.SystemId, src => src.Authentication.SystemID)
                .Map(dest => dest.SystemName, src => src.MessageHeader.SystemName)
                .Map(dest => dest.TraceNumber, src => src.MessageHeader.TraceNumber)
                .Map(dest => dest.TransactionCount, src => src.MessageHeader.TransactionCount)
                .Map(dest => dest.TransactionId, src => src.MessageHeader.TransactionID)
                .Map(dest => dest.TriggeredUser, src => src.Authentication.OriginalTriggeredUser)
                .Map(dest => dest.TriggeredUserOverride, src => src.Authentication.TriggeredUserOverride)
                .Map(dest => dest.UseClearingHouseBatchThrottle, src => src.MessageHeader.UseClearingHouseBatchThrottle)
                .Map(dest => dest.UserMnemonic, src => src.Authentication.UserMnemonic)
                .Map(dest => dest.UserTriggered, src => src.MessageHeader.UserTriggered)
                .Map(dest => dest.UseSelectedServiceType, src => src.MessageEvent.UseSelectedServiceType)
                .Map(dest => dest.VendorDataSource, src => src.MessageHeader.VendorDataSource)
                .Map(dest => dest.VendorId, src => src.MessageEvent.VendorId)
                .Map(dest => dest.VendorRequestedOverride, src => src.MessageHeader.VendorRequestedOverride)
                .Map(dest => dest.VendorRequestID, src => src.MessageHeader.VendorRequestID)
                .IgnoreNonMapped( true );
        }
    }
}
